/**
 * Brain Commerce Shopify Ingestor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Content model module.
 * @module model/Content
 * @version 0.2.0
 */
class Content {
    /**
     * Constructs a new <code>Content</code>.
     * @alias module:model/Content
     * @param title {String} 
     * @param content {String} 
     */
    constructor(title, content) { 
        
        Content.initialize(this, title, content);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, title, content) { 
        obj['title'] = title;
        obj['content'] = content;
    }

    /**
     * Constructs a <code>Content</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Content} obj Optional instance to populate.
     * @return {module:model/Content} The populated <code>Content</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Content();

            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('file_path')) {
                obj['file_path'] = ApiClient.convertToType(data['file_path'], 'String');
            }
            if (data.hasOwnProperty('internal_id')) {
                obj['internal_id'] = ApiClient.convertToType(data['internal_id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Content</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Content</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Content.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['uuid'] && !(typeof data['uuid'] === 'string' || data['uuid'] instanceof String)) {
            throw new Error("Expected the field `uuid` to be a primitive type in the JSON string but got " + data['uuid']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['content'] && !(typeof data['content'] === 'string' || data['content'] instanceof String)) {
            throw new Error("Expected the field `content` to be a primitive type in the JSON string but got " + data['content']);
        }
        // ensure the json data is a string
        if (data['file_path'] && !(typeof data['file_path'] === 'string' || data['file_path'] instanceof String)) {
            throw new Error("Expected the field `file_path` to be a primitive type in the JSON string but got " + data['file_path']);
        }

        return true;
    }


}

Content.RequiredProperties = ["title", "content"];

/**
 * @member {String} uuid
 */
Content.prototype['uuid'] = undefined;

/**
 * @member {String} title
 */
Content.prototype['title'] = undefined;

/**
 * @member {String} content
 */
Content.prototype['content'] = undefined;

/**
 * @member {String} file_path
 */
Content.prototype['file_path'] = undefined;

/**
 * @member {Number} internal_id
 */
Content.prototype['internal_id'] = undefined;






export default Content;

