/**
 * Brain Commerce Shopify Ingestor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProductIngestorStatus model module.
 * @module model/ProductIngestorStatus
 * @version 0.2.0
 */
class ProductIngestorStatus {
    /**
     * Constructs a new <code>ProductIngestorStatus</code>.
     * @alias module:model/ProductIngestorStatus
     */
    constructor() { 
        
        ProductIngestorStatus.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductIngestorStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductIngestorStatus} obj Optional instance to populate.
     * @return {module:model/ProductIngestorStatus} The populated <code>ProductIngestorStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductIngestorStatus();

            if (data.hasOwnProperty('started_at')) {
                obj['started_at'] = ApiClient.convertToType(data['started_at'], 'Date');
            }
            if (data.hasOwnProperty('finished_at')) {
                obj['finished_at'] = ApiClient.convertToType(data['finished_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('products_to_process')) {
                obj['products_to_process'] = ApiClient.convertToType(data['products_to_process'], 'Number');
            }
            if (data.hasOwnProperty('product_processed')) {
                obj['product_processed'] = ApiClient.convertToType(data['product_processed'], 'Number');
            }
            if (data.hasOwnProperty('batch_to_processed')) {
                obj['batch_to_processed'] = ApiClient.convertToType(data['batch_to_processed'], 'Number');
            }
            if (data.hasOwnProperty('batch_processed')) {
                obj['batch_processed'] = ApiClient.convertToType(data['batch_processed'], 'Number');
            }
            if (data.hasOwnProperty('current_batch')) {
                obj['current_batch'] = ApiClient.convertToType(data['current_batch'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('previous_page_url')) {
                obj['previous_page_url'] = ApiClient.convertToType(data['previous_page_url'], 'String');
            }
            if (data.hasOwnProperty('next_page_url')) {
                obj['next_page_url'] = ApiClient.convertToType(data['next_page_url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductIngestorStatus</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductIngestorStatus</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['previous_page_url'] && !(typeof data['previous_page_url'] === 'string' || data['previous_page_url'] instanceof String)) {
            throw new Error("Expected the field `previous_page_url` to be a primitive type in the JSON string but got " + data['previous_page_url']);
        }
        // ensure the json data is a string
        if (data['next_page_url'] && !(typeof data['next_page_url'] === 'string' || data['next_page_url'] instanceof String)) {
            throw new Error("Expected the field `next_page_url` to be a primitive type in the JSON string but got " + data['next_page_url']);
        }

        return true;
    }


}



/**
 * @member {Date} started_at
 */
ProductIngestorStatus.prototype['started_at'] = undefined;

/**
 * @member {Date} finished_at
 */
ProductIngestorStatus.prototype['finished_at'] = undefined;

/**
 * @member {Date} updated_at
 */
ProductIngestorStatus.prototype['updated_at'] = undefined;

/**
 * @member {Number} products_to_process
 */
ProductIngestorStatus.prototype['products_to_process'] = undefined;

/**
 * @member {Number} product_processed
 */
ProductIngestorStatus.prototype['product_processed'] = undefined;

/**
 * @member {Number} batch_to_processed
 */
ProductIngestorStatus.prototype['batch_to_processed'] = undefined;

/**
 * @member {Number} batch_processed
 */
ProductIngestorStatus.prototype['batch_processed'] = undefined;

/**
 * @member {Number} current_batch
 */
ProductIngestorStatus.prototype['current_batch'] = undefined;

/**
 * @member {String} status
 */
ProductIngestorStatus.prototype['status'] = undefined;

/**
 * @member {String} previous_page_url
 */
ProductIngestorStatus.prototype['previous_page_url'] = undefined;

/**
 * @member {String} next_page_url
 */
ProductIngestorStatus.prototype['next_page_url'] = undefined;






export default ProductIngestorStatus;

