/**
 * Brain Commerce Shopify Ingestor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ProductAvailability.
* @enum {}
* @readonly
*/
export default class ProductAvailability {
    
        /**
         * value: "in_stock"
         * @const
         */
        "in_stock" = "in_stock";

    
        /**
         * value: "out_of_stock"
         * @const
         */
        "out_of_stock" = "out_of_stock";

    

    /**
    * Returns a <code>ProductAvailability</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ProductAvailability} The enum <code>ProductAvailability</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

