/**
 * Merchant store api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Faq from '../model/Faq';
import HTTPValidationError from '../model/HTTPValidationError';

/**
* Faq service.
* @module api/FaqApi
* @version 0.2.1
*/
export default class FaqApi {

    /**
    * Constructs a new FaqApi. 
    * @alias module:api/FaqApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Check If Faq Collection Exists.
     * Returns true if FAQ collection exists else return false
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    checkIfFAQCollectionExistsV1FaqsCollectionExistsGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/faqs/collection-exists', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Check If Faq Collection Exists.
     * Returns true if FAQ collection exists else return false
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    checkIfFAQCollectionExistsV1FaqsCollectionExistsGet() {
      return this.checkIfFAQCollectionExistsV1FaqsCollectionExistsGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create Faq By Question
     * Create FAQ by question
     * @param {String} question 
     * @param {module:model/Faq} faq 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Faq} and HTTP response
     */
    createFAQByQuestionV1FaqsQuestionPostWithHttpInfo(question, faq) {
      let postBody = faq;
      // verify the required parameter 'question' is set
      if (question === undefined || question === null) {
        throw new Error("Missing the required parameter 'question' when calling createFAQByQuestionV1FaqsQuestionPost");
      }
      // verify the required parameter 'faq' is set
      if (faq === undefined || faq === null) {
        throw new Error("Missing the required parameter 'faq' when calling createFAQByQuestionV1FaqsQuestionPost");
      }

      let pathParams = {
        'question': question
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Faq;
      return this.apiClient.callApi(
        '/v1/faqs/{question}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create Faq By Question
     * Create FAQ by question
     * @param {String} question 
     * @param {module:model/Faq} faq 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Faq}
     */
    createFAQByQuestionV1FaqsQuestionPost(question, faq) {
      return this.createFAQByQuestionV1FaqsQuestionPostWithHttpInfo(question, faq)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create Faq Collection
     * Creates FAQ collection/schema in Weaviate database
     * @param {Object} opts Optional parameters
     * @param {Boolean} [delete_existing_collection = false)] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    createFAQCollectionV1FaqsCollectionPostWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'delete_existing_collection': opts['delete_existing_collection']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/faqs/collection', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create Faq Collection
     * Creates FAQ collection/schema in Weaviate database
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.delete_existing_collection  (default to false)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    createFAQCollectionV1FaqsCollectionPost(opts) {
      return this.createFAQCollectionV1FaqsCollectionPostWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete Faq By Internal Id
     * Delete FAQ by internal_id
     * @param {Number} internal_id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Boolean} and HTTP response
     */
    deleteFAQByInternalIdV1FaqsByInternalIdInternalIdDeleteWithHttpInfo(internal_id) {
      let postBody = null;
      // verify the required parameter 'internal_id' is set
      if (internal_id === undefined || internal_id === null) {
        throw new Error("Missing the required parameter 'internal_id' when calling deleteFAQByInternalIdV1FaqsByInternalIdInternalIdDelete");
      }

      let pathParams = {
        'internal_id': internal_id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = 'Boolean';
      return this.apiClient.callApi(
        '/v1/faqs/by-internal-id/{internal_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete Faq By Internal Id
     * Delete FAQ by internal_id
     * @param {Number} internal_id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Boolean}
     */
    deleteFAQByInternalIdV1FaqsByInternalIdInternalIdDelete(internal_id) {
      return this.deleteFAQByInternalIdV1FaqsByInternalIdInternalIdDeleteWithHttpInfo(internal_id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete Faq By Question
     * Delete FAQ by question
     * @param {String} question 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Boolean} and HTTP response
     */
    deleteFAQByQuestionV1FaqsQuestionDeleteWithHttpInfo(question) {
      let postBody = null;
      // verify the required parameter 'question' is set
      if (question === undefined || question === null) {
        throw new Error("Missing the required parameter 'question' when calling deleteFAQByQuestionV1FaqsQuestionDelete");
      }

      let pathParams = {
        'question': question
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = 'Boolean';
      return this.apiClient.callApi(
        '/v1/faqs/{question}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete Faq By Question
     * Delete FAQ by question
     * @param {String} question 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Boolean}
     */
    deleteFAQByQuestionV1FaqsQuestionDelete(question) {
      return this.deleteFAQByQuestionV1FaqsQuestionDeleteWithHttpInfo(question)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete Faq Collection
     * Delete FAQ collection
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Boolean} and HTTP response
     */
    deleteFAQCollectionV1FaqsCollectionDeleteWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = 'Boolean';
      return this.apiClient.callApi(
        '/v1/faqs/collection', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete Faq Collection
     * Delete FAQ collection
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Boolean}
     */
    deleteFAQCollectionV1FaqsCollectionDelete() {
      return this.deleteFAQCollectionV1FaqsCollectionDeleteWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Deletes All Faq From Collection
     * Deletes all FAQ from collection.
     * @param {Object} opts Optional parameters
     * @param {Boolean} [dry_run = false)] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    deletesAllFAQFromCollectionV1FaqsResetCollectionDeleteWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'dry_run': opts['dry_run']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/faqs/reset-collection', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Deletes All Faq From Collection
     * Deletes all FAQ from collection.
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.dry_run  (default to false)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    deletesAllFAQFromCollectionV1FaqsResetCollectionDelete(opts) {
      return this.deletesAllFAQFromCollectionV1FaqsResetCollectionDeleteWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get All Faqs
     * Returns All FAQs. If collection has a large number of FAQs                 response may take long time
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/Faq>} and HTTP response
     */
    getAllFAQsV1FaqsGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Faq];
      return this.apiClient.callApi(
        '/v1/faqs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get All Faqs
     * Returns All FAQs. If collection has a large number of FAQs                 response may take long time
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/Faq>}
     */
    getAllFAQsV1FaqsGet() {
      return this.getAllFAQsV1FaqsGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Faq By Question
     * Get FAQ by question
     * @param {String} question 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Faq} and HTTP response
     */
    getFAQByQuestionV1FaqsQuestionGetWithHttpInfo(question) {
      let postBody = null;
      // verify the required parameter 'question' is set
      if (question === undefined || question === null) {
        throw new Error("Missing the required parameter 'question' when calling getFAQByQuestionV1FaqsQuestionGet");
      }

      let pathParams = {
        'question': question
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Faq;
      return this.apiClient.callApi(
        '/v1/faqs/{question}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Faq By Question
     * Get FAQ by question
     * @param {String} question 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Faq}
     */
    getFAQByQuestionV1FaqsQuestionGet(question) {
      return this.getFAQByQuestionV1FaqsQuestionGetWithHttpInfo(question)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Import Multiple Faqs
     * Import multiple FAQs. If a FAQ same question already exist, it is updated. Otherwise new FAQ is created
     * @param {Array.<module:model/Faq>} faq 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/Faq>} and HTTP response
     */
    importMultipleFAQsV1FaqsPostWithHttpInfo(faq) {
      let postBody = faq;
      // verify the required parameter 'faq' is set
      if (faq === undefined || faq === null) {
        throw new Error("Missing the required parameter 'faq' when calling importMultipleFAQsV1FaqsPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [Faq];
      return this.apiClient.callApi(
        '/v1/faqs', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Import Multiple Faqs
     * Import multiple FAQs. If a FAQ same question already exist, it is updated. Otherwise new FAQ is created
     * @param {Array.<module:model/Faq>} faq 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/Faq>}
     */
    importMultipleFAQsV1FaqsPost(faq) {
      return this.importMultipleFAQsV1FaqsPostWithHttpInfo(faq)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update Faq By Question
     * Update FAQ By question
     * @param {String} question 
     * @param {module:model/Faq} faq 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Faq} and HTTP response
     */
    updateFAQByQuestionV1FaqsQuestionPutWithHttpInfo(question, faq) {
      let postBody = faq;
      // verify the required parameter 'question' is set
      if (question === undefined || question === null) {
        throw new Error("Missing the required parameter 'question' when calling updateFAQByQuestionV1FaqsQuestionPut");
      }
      // verify the required parameter 'faq' is set
      if (faq === undefined || faq === null) {
        throw new Error("Missing the required parameter 'faq' when calling updateFAQByQuestionV1FaqsQuestionPut");
      }

      let pathParams = {
        'question': question
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Faq;
      return this.apiClient.callApi(
        '/v1/faqs/{question}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Update Faq By Question
     * Update FAQ By question
     * @param {String} question 
     * @param {module:model/Faq} faq 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Faq}
     */
    updateFAQByQuestionV1FaqsQuestionPut(question, faq) {
      return this.updateFAQByQuestionV1FaqsQuestionPutWithHttpInfo(question, faq)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
