/**
 * Merchant store api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import HTTPValidationError from '../model/HTTPValidationError';
import Product from '../model/Product';

/**
* Product service.
* @module api/ProductApi
* @version 0.2.2
*/
export default class ProductApi {

    /**
    * Constructs a new ProductApi.
    * @alias module:api/ProductApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Check If Product Collection Exists.
     * Returns true if product collection exists else return false
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    checkIfProductCollectionExistsV1ProductsCollectionExistsGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/products/collection-exists', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Check If Product Collection Exists.
     * Returns true if product collection exists else return false
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    checkIfProductCollectionExistsV1ProductsCollectionExistsGet() {
      return this.checkIfProductCollectionExistsV1ProductsCollectionExistsGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create Product By Sku
     * Create Product by SKU
     * @param {String} sku
     * @param {module:model/Product} product
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Product} and HTTP response
     */
    createProductBySKUV1ProductsSkuPostWithHttpInfo(sku, product) {
      let postBody = product;
      // verify the required parameter 'sku' is set
      if (sku === undefined || sku === null) {
        throw new Error("Missing the required parameter 'sku' when calling createProductBySKUV1ProductsSkuPost");
      }
      // verify the required parameter 'product' is set
      if (product === undefined || product === null) {
        throw new Error("Missing the required parameter 'product' when calling createProductBySKUV1ProductsSkuPost");
      }

      let pathParams = {
        'sku': sku
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Product;
      return this.apiClient.callApi(
        '/v1/products/{sku}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create Product By Sku
     * Create Product by SKU
     * @param {String} sku
     * @param {module:model/Product} product
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Product}
     */
    createProductBySKUV1ProductsSkuPost(sku, product) {
      return this.createProductBySKUV1ProductsSkuPostWithHttpInfo(sku, product)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create Product Collection
     * Creates product collection/schema in Weaviate database
     * @param {Object} opts Optional parameters
     * @param {Boolean} [delete_existing_collection = false)]
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    createProductCollectionV1ProductsCollectionPostWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'delete_existing_collection': opts['delete_existing_collection']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/products/collection', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create Product Collection
     * Creates product collection/schema in Weaviate database
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.delete_existing_collection  (default to false)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    createProductCollectionV1ProductsCollectionPost(opts) {
      return this.createProductCollectionV1ProductsCollectionPostWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete Product By Internal Id
     * Delete product by internal_id
     * @param {Number} internal_id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Boolean} and HTTP response
     */
    deleteProductByInternalIdV1ProductsByInternalIdInternalIdDeleteWithHttpInfo(internal_id) {
      let postBody = null;
      // verify the required parameter 'internal_id' is set
      if (internal_id === undefined || internal_id === null) {
        throw new Error("Missing the required parameter 'internal_id' when calling deleteProductByInternalIdV1ProductsByInternalIdInternalIdDelete");
      }

      let pathParams = {
        'internal_id': internal_id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = 'Boolean';
      return this.apiClient.callApi(
        '/v1/products/by-internal-id/{internal_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete Product By Internal Id
     * Delete product by internal_id
     * @param {Number} internal_id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Boolean}
     */
    deleteProductByInternalIdV1ProductsByInternalIdInternalIdDelete(internal_id) {
      return this.deleteProductByInternalIdV1ProductsByInternalIdInternalIdDeleteWithHttpInfo(internal_id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete Product By Item Group Id
     * Delete product by item_group_id
     * @param {String} item_group_id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Boolean} and HTTP response
     */
    deleteProductByItemGroupIdWithHttpInfo(item_group_id) {
      let postBody = null;
      // verify the required parameter 'item_group_id' is set
      if (item_group_id === undefined || item_group_id === null) {
        throw new Error("Missing the required parameter 'item_group_id' when calling deleteProductByItemGroupId");
      }

      let pathParams = {
        'item_group_id': item_group_id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = 'Boolean';
      return this.apiClient.callApi(
        '/v1/products/item-group/{item_group_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete Product By Item Group Id
     * Delete product by item_group_id
     * @param {String} item_group_id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Boolean}
     */
    deleteProductByItemGroupId(item_group_id) {
      return this.deleteProductByItemGroupIdWithHttpInfo(item_group_id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete Product By Sku
     * Delete product by SKU
     * @param {String} sku
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Boolean} and HTTP response
     */
    deleteProductBySKUV1ProductsSkuDeleteWithHttpInfo(sku) {
      let postBody = null;
      // verify the required parameter 'sku' is set
      if (sku === undefined || sku === null) {
        throw new Error("Missing the required parameter 'sku' when calling deleteProductBySKUV1ProductsSkuDelete");
      }

      let pathParams = {
        'sku': sku
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = 'Boolean';
      return this.apiClient.callApi(
        '/v1/products/{sku}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete Product By Sku
     * Delete product by SKU
     * @param {String} sku
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Boolean}
     */
    deleteProductBySKUV1ProductsSkuDelete(sku) {
      return this.deleteProductBySKUV1ProductsSkuDeleteWithHttpInfo(sku)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete Product Collection
     * Delete product collection
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Boolean} and HTTP response
     */
    deleteProductCollectionV1ProductsCollectionDeleteWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = 'Boolean';
      return this.apiClient.callApi(
        '/v1/products/collection', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete Product Collection
     * Delete product collection
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Boolean}
     */
    deleteProductCollectionV1ProductsCollectionDelete() {
      return this.deleteProductCollectionV1ProductsCollectionDeleteWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Deletes All Products From Collection
     * Deletes all products from the Weaviate product.
     * @param {Object} opts Optional parameters
     * @param {Boolean} [dry_run = true)]
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    deletesAllProductsFromCollectionV1ProductsResetCollectionDeleteWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'dry_run': opts['dry_run']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/products/reset-collection', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Deletes All Products From Collection
     * Deletes all products from the Weaviate product.
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.dry_run  (default to true)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    deletesAllProductsFromCollectionV1ProductsResetCollectionDelete(opts) {
      return this.deletesAllProductsFromCollectionV1ProductsResetCollectionDeleteWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get All Products
     * Returns All Products. If collection has a large number of products, response may take long time
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/Product>} and HTTP response
     */
    getAllProductsV1ProductsGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Product];
      return this.apiClient.callApi(
        '/v1/products', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get All Products
     * Returns All Products. If collection has a large number of products, response may take long time
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/Product>}
     */
    getAllProductsV1ProductsGet() {
      return this.getAllProductsV1ProductsGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Product By Sku
     * Get Product by SKU
     * @param {String} sku
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Product} and HTTP response
     */
    getProductBySKUV1ProductsSkuGetWithHttpInfo(sku) {
      let postBody = null;
      // verify the required parameter 'sku' is set
      if (sku === undefined || sku === null) {
        throw new Error("Missing the required parameter 'sku' when calling getProductBySKUV1ProductsSkuGet");
      }

      let pathParams = {
        'sku': sku
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Product;
      return this.apiClient.callApi(
        '/v1/products/{sku}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Product By Sku
     * Get Product by SKU
     * @param {String} sku
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Product}
     */
    getProductBySKUV1ProductsSkuGet(sku) {
      return this.getProductBySKUV1ProductsSkuGetWithHttpInfo(sku)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Import Multiple Products
     * Import multiple products. If a product already exist, it is update. Otherwise new product is created
     * @param {Array.<module:model/Product>} product
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<Object>} and HTTP response
     */
    importMultipleProductsV1ProductsPostWithHttpInfo(product) {
      let postBody = product;
      // verify the required parameter 'product' is set
      if (product === undefined || product === null) {
        throw new Error("Missing the required parameter 'product' when calling importMultipleProductsV1ProductsPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [Object];
      return this.apiClient.callApi(
        '/v1/products', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Import Multiple Products
     * Import multiple products. If a product already exist, it is update. Otherwise new product is created
     * @param {Array.<module:model/Product>} product
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<Object>}
     */
    importMultipleProductsV1ProductsPost(product) {
      return this.importMultipleProductsV1ProductsPostWithHttpInfo(product)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update Product By Sku
     * Update Product By SKU
     * @param {String} sku
     * @param {module:model/Product} product
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Product} and HTTP response
     */
    updateProductBySKUV1ProductsSkuPutWithHttpInfo(sku, product) {
      let postBody = product;
      // verify the required parameter 'sku' is set
      if (sku === undefined || sku === null) {
        throw new Error("Missing the required parameter 'sku' when calling updateProductBySKUV1ProductsSkuPut");
      }
      // verify the required parameter 'product' is set
      if (product === undefined || product === null) {
        throw new Error("Missing the required parameter 'product' when calling updateProductBySKUV1ProductsSkuPut");
      }

      let pathParams = {
        'sku': sku
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Product;
      return this.apiClient.callApi(
        '/v1/products/{sku}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Update Product By Sku
     * Update Product By SKU
     * @param {String} sku
     * @param {module:model/Product} product
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Product}
     */
    updateProductBySKUV1ProductsSkuPut(sku, product) {
      return this.updateProductBySKUV1ProductsSkuPutWithHttpInfo(sku, product)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
