/**
 * Brain Commerce Shopify Ingestor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BrainCommerceShopifyIngestorApi);
  }
}(this, function(expect, BrainCommerceShopifyIngestorApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BrainCommerceShopifyIngestorApi.Product();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Product', function() {
    it('should create an instance of Product', function() {
      // uncomment below and update the code to test Product
      //var instance = new BrainCommerceShopifyIngestorApi.Product();
      //expect(instance).to.be.a(BrainCommerceShopifyIngestorApi.Product);
    });

    it('should have the property uuid (base name: "uuid")', function() {
      // uncomment below and update the code to test the property uuid
      //var instance = new BrainCommerceShopifyIngestorApi.Product();
      //expect(instance).to.be();
    });

    it('should have the property sku (base name: "sku")', function() {
      // uncomment below and update the code to test the property sku
      //var instance = new BrainCommerceShopifyIngestorApi.Product();
      //expect(instance).to.be();
    });

    it('should have the property sku_id (base name: "sku_id")', function() {
      // uncomment below and update the code to test the property sku_id
      //var instance = new BrainCommerceShopifyIngestorApi.Product();
      //expect(instance).to.be();
    });

    it('should have the property product_category (base name: "product_category")', function() {
      // uncomment below and update the code to test the property product_category
      //var instance = new BrainCommerceShopifyIngestorApi.Product();
      //expect(instance).to.be();
    });

    it('should have the property internal_id (base name: "internal_id")', function() {
      // uncomment below and update the code to test the property internal_id
      //var instance = new BrainCommerceShopifyIngestorApi.Product();
      //expect(instance).to.be();
    });

    it('should have the property availability (base name: "availability")', function() {
      // uncomment below and update the code to test the property availability
      //var instance = new BrainCommerceShopifyIngestorApi.Product();
      //expect(instance).to.be();
    });

    it('should have the property price (base name: "price")', function() {
      // uncomment below and update the code to test the property price
      //var instance = new BrainCommerceShopifyIngestorApi.Product();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instance = new BrainCommerceShopifyIngestorApi.Product();
      //expect(instance).to.be();
    });

    it('should have the property item_group_id (base name: "item_group_id")', function() {
      // uncomment below and update the code to test the property item_group_id
      //var instance = new BrainCommerceShopifyIngestorApi.Product();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new BrainCommerceShopifyIngestorApi.Product();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new BrainCommerceShopifyIngestorApi.Product();
      //expect(instance).to.be();
    });

    it('should have the property gender (base name: "gender")', function() {
      // uncomment below and update the code to test the property gender
      //var instance = new BrainCommerceShopifyIngestorApi.Product();
      //expect(instance).to.be();
    });

    it('should have the property image_link (base name: "image_link")', function() {
      // uncomment below and update the code to test the property image_link
      //var instance = new BrainCommerceShopifyIngestorApi.Product();
      //expect(instance).to.be();
    });

    it('should have the property material (base name: "material")', function() {
      // uncomment below and update the code to test the property material
      //var instance = new BrainCommerceShopifyIngestorApi.Product();
      //expect(instance).to.be();
    });

    it('should have the property pattern (base name: "pattern")', function() {
      // uncomment below and update the code to test the property pattern
      //var instance = new BrainCommerceShopifyIngestorApi.Product();
      //expect(instance).to.be();
    });

    it('should have the property product_weight (base name: "product_weight")', function() {
      // uncomment below and update the code to test the property product_weight
      //var instance = new BrainCommerceShopifyIngestorApi.Product();
      //expect(instance).to.be();
    });

    it('should have the property size (base name: "size")', function() {
      // uncomment below and update the code to test the property size
      //var instance = new BrainCommerceShopifyIngestorApi.Product();
      //expect(instance).to.be();
    });

    it('should have the property color (base name: "color")', function() {
      // uncomment below and update the code to test the property color
      //var instance = new BrainCommerceShopifyIngestorApi.Product();
      //expect(instance).to.be();
    });

    it('should have the property system_link (base name: "system_link")', function() {
      // uncomment below and update the code to test the property system_link
      //var instance = new BrainCommerceShopifyIngestorApi.Product();
      //expect(instance).to.be();
    });

    it('should have the property link (base name: "link")', function() {
      // uncomment below and update the code to test the property link
      //var instance = new BrainCommerceShopifyIngestorApi.Product();
      //expect(instance).to.be();
    });

    it('should have the property brand (base name: "brand")', function() {
      // uncomment below and update the code to test the property brand
      //var instance = new BrainCommerceShopifyIngestorApi.Product();
      //expect(instance).to.be();
    });

    it('should have the property model (base name: "model")', function() {
      // uncomment below and update the code to test the property model
      //var instance = new BrainCommerceShopifyIngestorApi.Product();
      //expect(instance).to.be();
    });

    it('should have the property gtin (base name: "gtin")', function() {
      // uncomment below and update the code to test the property gtin
      //var instance = new BrainCommerceShopifyIngestorApi.Product();
      //expect(instance).to.be();
    });

    it('should have the property condition (base name: "condition")', function() {
      // uncomment below and update the code to test the property condition
      //var instance = new BrainCommerceShopifyIngestorApi.Product();
      //expect(instance).to.be();
    });

    it('should have the property adult (base name: "adult")', function() {
      // uncomment below and update the code to test the property adult
      //var instance = new BrainCommerceShopifyIngestorApi.Product();
      //expect(instance).to.be();
    });

    it('should have the property review_summaries (base name: "review_summaries")', function() {
      // uncomment below and update the code to test the property review_summaries
      //var instance = new BrainCommerceShopifyIngestorApi.Product();
      //expect(instance).to.be();
    });

    it('should have the property average_rating (base name: "average_rating")', function() {
      // uncomment below and update the code to test the property average_rating
      //var instance = new BrainCommerceShopifyIngestorApi.Product();
      //expect(instance).to.be();
    });

  });

}));
