/**
 * Brain Commerce Shopify Ingestor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BrainCommerceShopifyIngestorApi);
  }
}(this, function(expect, BrainCommerceShopifyIngestorApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BrainCommerceShopifyIngestorApi.ProductApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProductApi', function() {
    describe('collectionExists', function() {
      it('should call collectionExists successfully', function(done) {
        //uncomment below and update the code to test collectionExists
        //instance.collectionExists(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createCollection', function() {
      it('should call createCollection successfully', function(done) {
        //uncomment below and update the code to test createCollection
        //instance.createCollection(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createProductBySku', function() {
      it('should call createProductBySku successfully', function(done) {
        //uncomment below and update the code to test createProductBySku
        //instance.createProductBySku(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCollection', function() {
      it('should call deleteCollection successfully', function(done) {
        //uncomment below and update the code to test deleteCollection
        //instance.deleteCollection(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteProductByInternalId', function() {
      it('should call deleteProductByInternalId successfully', function(done) {
        //uncomment below and update the code to test deleteProductByInternalId
        //instance.deleteProductByInternalId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteProductBySku', function() {
      it('should call deleteProductBySku successfully', function(done) {
        //uncomment below and update the code to test deleteProductBySku
        //instance.deleteProductBySku(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllProducts', function() {
      it('should call getAllProducts successfully', function(done) {
        //uncomment below and update the code to test getAllProducts
        //instance.getAllProducts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getProductBySku', function() {
      it('should call getProductBySku successfully', function(done) {
        //uncomment below and update the code to test getProductBySku
        //instance.getProductBySku(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('importMultipleProducts', function() {
      it('should call importMultipleProducts successfully', function(done) {
        //uncomment below and update the code to test importMultipleProducts
        //instance.importMultipleProducts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('resetProductCollection', function() {
      it('should call resetProductCollection successfully', function(done) {
        //uncomment below and update the code to test resetProductCollection
        //instance.resetProductCollection(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateProductBySku', function() {
      it('should call updateProductBySku successfully', function(done) {
        //uncomment below and update the code to test updateProductBySku
        //instance.updateProductBySku(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
